# Generated by Django 2.2.16 on 2020-10-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, default='Família', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Galeria',
                'verbose_name_plural': 'Categorias de Galeria',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referencia')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='Noiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/300x300', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arquivo de Foto')),
            ],
            options={
                'verbose_name': 'Noiva',
                'verbose_name_plural': 'Noiva',
            },
        ),
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/300x300', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Noivo',
                'verbose_name_plural': 'Noivo',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Contador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('foto_background_url', models.URLField(blank=True, default='https://imgur.com/WvzW9gn.jpg', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contador',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('frase', models.TextField(blank=True, null=True)),
                ('foto_background_url', models.URLField(blank=True, default='https://imgur.com/nMHYQd9.jpg', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background')),
            ],
            options={
                'verbose_name': 'Pagina de Footer',
                'verbose_name_plural': 'Pagina de Footer',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('frase', models.TextField(blank=True, default='Será uma honra ter você no momento mais incrível das nossas vidas, onde finalmente nos tornaremos um.', null=True)),
                ('foto_background_url', models.URLField(blank=True, default='https://imgur.com/QnAo2qj.jpg', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background')),
            ],
            options={
                'verbose_name': 'Pagina de Frase Principal',
                'verbose_name_plural': 'Pagina de Frase Principal',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Galeria de Fotos', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, default='Nada melhor do que fotos pra registrar tudo!', null=True)),
            ],
            options={
                'verbose_name': 'Pagina de Galeria',
                'verbose_name_plural': 'Pagina de Galeria',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('frase', models.TextField(blank=True, default='Vamos nos casar!', null=True)),
                ('foto_background_url', models.URLField(blank=True, default='https://i.imgur.com/jWXZF4z.jpg', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background')),
            ],
            options={
                'verbose_name': 'Pagina de Inicio',
                'verbose_name_plural': 'Pagina de Inicio',
            },
        ),
        migrations.CreateModel(
            name='Pagina_ListaPresentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Lista de Presentes', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, default='Abaixo, estão as listas que fizemos online. Qualquer dúvida, só entrar em contato com a gente!', null=True)),
                ('foto_background_url', models.URLField(blank=True, default='https://imgur.com/UWpXoS1.jpg', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto Background')),
            ],
            options={
                'verbose_name': 'Pagina de Lista de Presentes',
                'verbose_name_plural': 'Pagina de Lista de Presentes',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Mural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Mural', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, default='Por favor, não saia deste site sem deixar um recado para nós. Sua mensagem é muito importante, e gostaríamos de recebê-la. Nós receberemos e publicaremos as melhores em nossa página.', null=True)),
            ],
            options={
                'verbose_name': 'Pagina de Mural',
                'verbose_name_plural': 'Pagina de Mural',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Noivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Os Noivos', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Pagina dos Noivos',
                'verbose_name_plural': 'Pagina dos Noivos',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Padrinhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Padrinhos', max_length=255, null=True)),
                ('frase', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pagina de Padrinhos',
                'verbose_name_plural': 'Pagina de Padrinhos',
            },
        ),
        migrations.CreateModel(
            name='Pagina_RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='RSVP', max_length=255, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pagina de RSVP',
                'verbose_name_plural': 'Pagina de RSVP',
            },
        ),
        migrations.CreateModel(
            name='Pagina_Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('titulo_menu', models.CharField(blank=True, default='Nossa História', max_length=255, null=True)),
                ('texto_historia', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pagina de Timeline',
                'verbose_name_plural': 'Pagina de Timeline',
            },
        ),
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('foto', models.URLField(blank=True, default='https://placehold.it/300x300', null=True)),
                ('texto', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recado',
                'verbose_name_plural': 'Recados',
            },
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cerimonia', models.BooleanField()),
                ('recepcao', models.BooleanField()),
                ('nome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('mensagem', models.TextField()),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': "RSVP's",
            },
        ),
        migrations.CreateModel(
            name='Recepcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('cor_casamento', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Endereco')),
            ],
            options={
                'verbose_name': 'Recepcao',
                'verbose_name_plural': 'Recepcao',
            },
        ),
        migrations.CreateModel(
            name='ItemTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/640x480', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pagina_Timeline')),
            ],
            options={
                'verbose_name': 'Item Timeline',
                'verbose_name_plural': 'Itens da Timeline',
            },
        ),
        migrations.CreateModel(
            name='ItemPadrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/640x480', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('pagina_padrinhos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pagina_Padrinhos')),
            ],
            options={
                'verbose_name': 'Item Padrinho',
                'verbose_name_plural': 'Padrinhos',
            },
        ),
        migrations.CreateModel(
            name='ItemListaPresentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_site', models.BooleanField(blank=True, default=True, null=True)),
                ('iframe', models.TextField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/640x480', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('pagina_listapresentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pagina_ListaPresentes')),
            ],
            options={
                'verbose_name': 'Item de Lista de Presentes',
                'verbose_name_plural': 'Itens de Lista de Presentes',
            },
        ),
        migrations.CreateModel(
            name='ItemGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('foto_url', models.URLField(blank=True, default='https://placehold.it/640x480', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CategoriaGaleria')),
                ('galeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pagina_Galeria')),
            ],
            options={
                'verbose_name': 'Item da Galeria',
                'verbose_name_plural': 'Itens da Galeria',
            },
        ),
    ]
